=== idimopoulos/validator-resources-assessment/resources/assessment/schemas/Assessment.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "description": "European Union Interoperability Act assessment report.",
  "required": [
    "name",
    "binding_requirement",
    "provider"
  ],
  "additionalProperties": false,
  "properties": {
    "id": {
      "schema": {
        "$ref": "common/UUID.schema.json"
      },
      "readOnly": true,
      "description": "The universally unique ID of the assessment report"
    },
    "uri": {
      "type": "string",
      "format": "uri",
      "readOnly": true,
      "description": "The canonical URI of the assessment report"
    },
    "name": {
      "type": "string",
      "description": "A short name assigned for easy identification.",
      "minLength": 1,
      "maxLength": 255
    },
    "provider": {
      "description": "A public organisation. For an existing organisationm pass its ID. To\ncreate a new organisation pass a `MemberStateOrganisation` object.\nIt's not possible to to create a new European Union organisation,\nyou should always pass an ID to refer one. To find out which are all\nexisting organisations, use the `/organisation` GET resource,\ndocumented in this page.",
      "oneOf": [
        {
          "$ref": "common/MemberStateOrganisation.schema.json"
        },
        {
          "$ref": "common/UUID.schema.json"
        }
      ]
    },
    "relevant_report": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "format": "uri"
      },
      "description": "Relevant assessment reports"
    },
    "binding_requirement": {
      "description": "One ore multiple objects can be submitted, each following the\nBindingRequirement schema.",
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "$ref": "common/BindingRequirement.schema.json"
      }
    },
    "results_in": {
      "type": "object",
      "description": "Identified effects on cross-border interoperability from different\nperspectives: legal, organisational, semantic, and technical.",
      "properties": {
        "legal": {
          "$ref": "common/Statement.schema.json"
        },
        "organisational": {
          "$ref": "common/Statement.schema.json"
        },
        "semantic": {
          "$ref": "common/Statement.schema.json"
        },
        "technical": {
          "$ref": "common/Statement.schema.json"
        }
      }
    },
    "remaining_barriers": {
      "type": "string",
      "description": "Describe possible remaining barriers to interoperability."
    },
    "documents": {
      "type": "array",
      "uniqueItems": true,
      "description": "List of URLs of documents supporting this assessment report.",
      "items": {
        "type": "string",
        "format": "uri"
      }
    },
    "other_comment": {
      "type": "string",
      "description": "Any additional comments or notes about the assessment."
    }
  }
}

=== idimopoulos/validator-resources-assessment/resources/assessment/tests/valid/submit-create-or-refer-sub-objects.json
{
  "name": "Legislation waste management",
  "provider": {
    "name": "City of Brussels",
    "organisation_type": "local_public_sector_body",
    "country": "BE"
  },
  "relevant_report": [
    "https://example.com/last-year-report",
    "https://example.com/middle-east"
  ],
  "binding_requirement": [
    {
      "expression": [
        {
          "name": "Legal Act 2024",
          "description": "Reference to an EU legal expression",
          "documented_in": "https://example.com/eli/act"
        }
      ],
      "description": "Article 5",
      "documented_in": "https://example.com/eli/act",
      "documents": [
        "https://example.com/law/123",
        "https://example.com/regulation/eu-1655467-s"
      ],
      "affects": [
        {
          "name": "Digital Monitoring Unit",
          "thematic_area": [
            "general_public_services",
            "environmental_protection"
          ],
          "country": [
            "BE",
            "NL"
          ]
        },
        {
          "name": "Training Centre",
          "thematic_area": [
            "education"
          ],
          "country": [
            "BE"
          ]
        }
      ],
      "has_participation": [
        {
          "participant_type": [
            "national_public_sector_body"
          ],
          "country": [
            "BE",
            "NL",
            "LU"
          ]
        },
        {
          "participant_type": [
            "private_businesses"
          ],
          "country": [
            "IT"
          ]
        }
      ],
      "asset": [
        {
          "title": "Portal EU",
          "description": "An EU portal interoperable solution",
          "landing_page": "https://portal.example.eu"
        },
        "b21e876e-8ad0-4057-ad57-de45c51d374f",
        "a0e76022-863e-4f8f-8eb0-8227cd080be4"
      ]
    }
  ],
  "results_in": {
    "organisational": {
      "interpretation": "positive",
      "judgement": "Compliant with conditions"
    },
    "technical": {
      "interpretation": "neutral",
      "judgement": "Requires follow-up"
    }
  },
  "remaining_barriers": "The city has not yet implemented the new regulations.",
  "documents": [
    "https://files.example.com/documents/req-1.pdf",
    "https://files.example.com/documents/regulation.2025.pdf"
  ],
  "other_comment": "Still work to be done. Waiting for a new iteration."
}
